const Doctor = require("../models/Doctor");
const Patient = require("../models/Patient"); // 1. Added this import
const bcrypt = require("bcryptjs");
const jwt = require("jsonwebtoken");

// --- DOCTOR LOGIC ---

exports.registerDoctor = async (req, res) => {
  try {
    const { name, email, password, specialization, clinicName } = req.body;
    let doctor = await Doctor.findOne({ email });
    if (doctor) return res.status(400).json({ msg: "Doctor already registered" });

    doctor = new Doctor({ name, email, password, specialization, clinicName });
    const salt = await bcrypt.genSalt(10);
    doctor.password = await bcrypt.hash(password, salt);

    await doctor.save();
    const token = jwt.sign({ id: doctor._id, role: 'doctor' }, process.env.JWT_SECRET, { expiresIn: "1d" });

    res.json({
      token,
      doctor: {
        id: doctor._id,
        name: doctor.name,
        doctorId: doctor.doctorId,
        email: doctor.email,
        role: 'doctor'
      }
    });
  } catch (err) {
    console.error(err.message);
    res.status(500).send("Server error");
  }
};

exports.loginDoctor = async (req, res) => {
  try {
    const { email, password } = req.body;
    const doctor = await Doctor.findOne({ email });
    if (!doctor) return res.status(400).json({ msg: "Invalid Credentials" });

    const isMatch = await bcrypt.compare(password, doctor.password);
    if (!isMatch) return res.status(400).json({ msg: "Invalid Credentials" });

    const token = jwt.sign({ id: doctor._id, role: 'doctor' }, process.env.JWT_SECRET, { expiresIn: "1d" });

    res.json({
      token,
      doctor: {
        id: doctor._id,
        name: doctor.name,
        doctorId: doctor.doctorId,
        email: doctor.email,
        role: 'doctor'
      }
    });
  } catch (err) {
    res.status(500).send("Server error");
  }
};

// --- PATIENT LOGIC ---
// 1. Updated Registration Logic
exports.registerPatient = async (req, res) => {
  try {
    const { name, email, password, age, gender, contact } = req.body;

    // Check if user exists
    let patient = await Patient.findOne({ email });
    if (patient) return res.status(400).json({ msg: "User already exists" });

    // Create instance
    patient = new Patient({ name, email, password, age, gender, contact });

    // Hash Password
    const salt = await bcrypt.genSalt(10);
    patient.password = await bcrypt.hash(password, salt);

    await patient.save();

    // Generate Token
    const token = jwt.sign(
      { id: patient._id, role: 'patient' }, 
      process.env.JWT_SECRET, 
      { expiresIn: "7d" }
    );

    res.json({
      token,
      patient: {
        id: patient._id,
        name: patient.name,
        patientId: patient.patientId, // Auto-generated by your schema middleware
        email: patient.email,
        role: 'patient'
      }
    });
  } catch (err) {
    console.error("Registration Error:", err.message);
    res.status(500).send("Registration Error");
  }
};

// 2. Updated loginPatient logic
exports.loginPatient = async (req, res) => {
  try {
    const { patientId, password } = req.body;

    if (!patientId || !password) {
      return res.status(400).json({ msg: "Please enter all fields" });
    }

    // CRITICAL FIX: Added .select("+password") to retrieve the hidden field
    const patient = await Patient.findOne({ 
      patientId: patientId.toUpperCase() 
    }).select("+password");

    if (!patient) {
      return res.status(400).json({ msg: "Invalid Patient ID" });
    }

    // Safety Check: Ensure the database actually has a password for this record
    if (!patient.password) {
      return res.status(500).json({ msg: "Authentication data missing for this user" });
    }

    // Now bcrypt will receive (string, string) instead of (string, undefined)
    const isMatch = await bcrypt.compare(password, patient.password);
    if (!isMatch) return res.status(400).json({ msg: "Invalid Password" });

    const token = jwt.sign(
      { id: patient._id, role: 'patient' }, 
      process.env.JWT_SECRET, 
      { expiresIn: "7d" }
    );

    res.json({
      token,
      patient: {
        id: patient._id,
        name: patient.name,
        patientId: patient.patientId,
        email: patient.email,
        role: 'patient'
      }
    });
  } catch (err) {
    console.error("Login Error:", err.message);
    res.status(500).send("Login Error");
  }
};