const mongoose = require("mongoose");

const DiseaseSchema = new mongoose.Schema(
  {
    // Mapped from: 'Sr No.'
    NAMC_ID: { type: Number, required: true }, 
    
    // Mapped from: 'NAMC_CODE'
    NAMC_CODE: { type: String, required: true },

    // Mapped from: 'NAMC_term', 'NAMC_term_diacritical', 'NAMC_term_DEVANAGARI'
    NAMC_term: { type: String, required: true },
    NAMC_term_diacritical: { type: String },
    NAMC_term_DEVANAGARI: { type: String },
    
    // Mapped from: 'Short_definition', 'Long_definition', 'Ontology_branches'
    short_definition: { type: String },
    long_definition: { type: String },
    ontology_branches: { type: String },

    // --- NEW FIELDS ADDED FROM CSV ---
    // Mapped from: 'Name English'
    name_english: { type: String }, 
    
    // Mapped from: 'Name English Under Index'
    name_english_under_index: { type: String }, 
    
    // Mapped from: 'Primary Index Related'
    primary_index_related: { type: String }, 

    // --- Fields for ICD-11 and DeepSeek integration ---
    // Note: You can initially populate this from the 'ICD_11_code' column in your CSV
    ICD_11_code: { type: String, default: "Not Linked" },
    icd11Term: { type: String },
    
    // To be generated by DeepSeek / Gemini AI
    commonDescription: { type: String }, 
    matchingPercentage: { type: Number, default: 0 }, 
    symptoms: { type: [String], default: [] }
  },
  { timestamps: true }
);

module.exports = mongoose.model("Disease", DiseaseSchema);